// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/endaaman/api.endaaman.me/controllers"
	"github.com/endaaman/api.endaaman.me/infras"
	"github.com/endaaman/api.endaaman.me/routers"
	"github.com/endaaman/api.endaaman.me/usecases"
)

import (
	_ "github.com/endaaman/api.endaaman.me/routers"
)

// Injectors from injector.go:

func Inject() *routers.Router {
	articleRepository := infras.NewArticleRepository()
	articleUsecase := usecases.NewArticleUsecase(articleRepository)
	articleController := controllers.NewArticleController(articleUsecase)
	router := routers.RegisterRouter(articleController)
	return router
}
